### ISSUE TITLE
reproduce benchmark

### ISSUE THREAD

**Issue by setop** [mode80/yahtcbot#1]
The article says the execution time is 2.5 minutes. My attempt are more circa 20 minutes (probably more, I killed it before it ends).
What hardware are you benchmarking on ?

**Comment by mode80** [comment]
I've a 2021 10-core Macbook Pro M1 with 64 gb. But it only uses up to 6 threads/cores and I think memory use is around 4GB to cache all the lookup state as it runs. If you're memory constrained, it'll be quite a bit slower. Testing was with clang -O3 which works well with the inline SIMD hints. That makes for about a 3x speed difference. Not sure if GCC picks those up. 

You should see a % style progress indicator almost right away that gives you a sense of how long it'll take. If not, something probably very wrong.

**Comment by setop** [comment]
I'm not familiar with M1'architecture but 6t/c * 10c = 60 threads.
My machine is not memory constrained, 16GB. But can only provide 2*2 = 4 treads.
So I can forcaste 15 times slower. That is 40 minutes.
Thanks for the details, that explains a lot :)

BTW, thanks for the article. I was happy to see Nim win :)
